"感謝Steve Losh 大大這篇文章 (http://stevelosh.com/blog/2010/09/coming-home-to-vim/)讓我多了解了一些vimrc。

"環境設定
set nocp           "be iMproved 取消與vi相容 nocp
set so=3             "讓畫面上/下方永遠保有x行 so
set ai              "自動縮排 ai
set wmnu                "更強的自動補齊功能 wmnu
set bs=indent,eol,start  "消除鍵設定 bs
set incsearch               "漸進式搜尋
set hlsearch                "標示搜尋結果(輸入:nohls以消除標示)
"set linebreak               "讓vim不會在字間斷句，中文文章不必使用 lbr
set autoread                "自動讀取檢視中檔案更新


"tab設定
set ts=4               "tab縮排數 ts
set sw=4            "設定縮排指令(>或<)字元 sw
set sts=4           "設定tab鍵為x個空白字元 sts
set et               "以空白字元取代tab字元 et

"設定編碼
set enc=utf8           "設定編碼 enc
set gfn=consolas:h12    "設定字型 gfn
set lm=zh_TW.UTF-8    "設定語言 lm
language message zh_TW.UTF-8
set hlg=zh             "hlg

"顯示設定
set nu                  "顯示行號 nu
syntax on                   "語法反白
set bg=light        "底色(亮/暗) bg
set t_Co=256                "設定顏色為256色
colo munkeeGriin     "設定色彩配置 colo

filetype plugin indent on

"Folding
set foldenable
set foldmethod=indent
set filetype=html
set smartindent
let g:html_indent_inctags = "html,body,head,tbody,div,p,h3"

"Vundle外掛管理
filetype off                "required!關閉檔案類型外掛
 
set rtp+=~/vimfiles/bundle/vundle/  "set the runtime path to include Vundle
call vundle#rc()

"Let vundle manage vundle required!
Bundle 'gmarik/vundle'
"安裝Bundle
Bundle 'mattn/emmet-vim'
let g:user_emmet_expandabbr_key = ',,'
Bundle 'scrooloose/nerdtree'
Bundle 'bling/vim-airline'

filetype plugin indent on   "重新開啟檔案類型外掛+設定縮排!

"Always show statusline
set laststatus=2
au VimEnter *  NERDTree

Bundle 'godlygeek/tabular'          
"align text
Bundle 'plasticboy/vim-markdown'    
"markdown language highlight
"Bundle 'Yggdroot/indentLine'
"let g:indentLine_color_term=1
"let g:indentLine_color_gui = '#000000'

"Bundle 'shime/vim-livedown'
"Bundle 'suan/vim-instant-markdown'

"makdown force
autocmd BufNew,BufRead *.md set filetype=markdown

"goyo
Bundle 'junegunn/goyo.vim'
